version: '3.8'

services:
  app:
    image: 624545858643.dkr.ecr.ap-northeast-2.amazonaws.com/jeonggiju/life:latest
    container_name: jeonggiju-life-server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_ACCESS_KEY=${JWT_ACCESS_KEY}
      - JWT_REFRESH_KEY=${JWT_REFRESH_KEY}
    depends_on:
      - db
    networks:
      - app-network
  nginx:
    image: 624545858643.dkr.ecr.ap-northeast-2.amazonaws.com/jeonggiju/nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
      # - "443:443"  # HTTPS 사용 시
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  pgdata:
