version: '3.8'

services:
  app:
    image: 624545858643.dkr.ecr.ap-northeast-2.amazonaws.com/jeonggiju/life:latest
    container_name: jeonggiju-life-server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JWT_ACCESS_KEY=${JWT_ACCESS_KEY}
      - JWT_REFRESH_KEY=${JWT_REFRESH_KEY}

      - AWS_S3_ACCESS_KEY=${AWS_S3_ACCESS_KEY}
      - AWS_S3_SECRET_KEY=${AWS_S3_SECRET_KEY}
      - AWS_S3_REGION=${AWS_S3_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}

    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: 624545858643.dkr.ecr.ap-northeast-2.amazonaws.com/jeonggiju/nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - /home/ubuntu/certbot/conf:/etc/letsencrypt:ro
      - /home/ubuntu/certbot/www:/var/www/certbot:ro
    networks:
      - app-network
    depends_on:
      - app
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/ubuntu/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: