version: '3.8'

services:
  nginx:
    image: 624545858643.dkr.ecr.ap-northeast-2.amazonaws.com/jeonggiju/nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - /home/ubuntu/certbot/conf:/etc/letsencrypt:ro
      - /home/ubuntu/certbot/www:/var/www/certbot:ro
    networks:
      - app-network

networks:
  app-network:
    external: true

