FROM nginx:alpine

COPY ./nginx/conf/default.conf /etc/nginx/conf.d/default.conf

COPY ./nginx/static/ /usr/share/nginx/static/

RUN apk add --no-cache curl

RUN rm -f /etc/nginx/conf.d/default.conf.default

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]