services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/ubuntu/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/certbot/www:/var/www/certbot

  db:
    image: mysql:8.0
    container_name: mysql-db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app1234
      MYSQL_ROOT_PASSWORD: app1234root
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d:ro
    networks:
      - app-network
    restart: unless-stopped

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter
    environment:
      DATA_SOURCE_NAME: "app:app1234@(mysql-db:3306)/"
    ports:
      - "9104:9104"
    networks:
      - app-network
    restart: unless-stopped

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-exporter
    command:
      - '--nginx.scrape-uri=http://127.0.0.1/stub_status'
    network_mode: host
    # host 네트워크를 사용하므로 별도의 포트 매핑/도커 네트워크가 필요 없습니다.
    restart: unless-stopped

volumes:
  mysqldata:

networks:
  app-network:
    external: true
