services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/ubuntu/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/certbot/www:/var/www/certbot

  db:
    image: mysql:8.0
    container_name: mysql-db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d:ro
    networks:
      - app-network
    restart: unless-stopped

  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: mysql-exporter
    env_file:
      - .env
    environment:
      DATA_SOURCE_NAME: "${SPRING_DATASOURCE_USERNAME}:${SPRING_DATASOURCE_PASSWORD}@(mysql-db:3306)/app"
    ports:
      - "9104:9104"
    networks:
      - app-network
    restart: unless-stopped

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-exporter
    command:
      - '-nginx.scrape-uri=http://nginx-server:80/stub_status'
    ports:
      - "9113:9113"
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mysqldata:

networks:
  app-network:
    external: true
