version: '3.8'

services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/ubuntu/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/certbot/www:/var/www/certbot

  db:
    image: postgres:16
    container_name: postgres-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    networks:
      - app-network
    restart: unless-stopped

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    env_file:
      - .env
    environment:
      DATA_SOURCE_NAME: "postgresql://${SPRING_DATASOURCE_USERNAME}:${SPRING_DATASOURCE_PASSWORD}@postgres-db:5432/app?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - app-network
    restart: unless-stopped

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-exporter
    command:
      - '-nginx.scrape-uri=http://nginx-server:80/stub_status'
    ports:
      - "9113:9113"
    networks:
      - app-network
    restart: unless-stopped

volumes:
  pgdata:
    external:
      name: jeonggiju-life_pgdata

networks:
  app-network:
    external: true