app:
  cookie:
    secure: ${APP_COOKIE_SECURE}

spring:
  application:
    name: jeonggiju
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      cache:
        period: 86400
        cachecontrol:
          max-age: 86400
          cache-public: true

server:
  address: 0.0.0.0
  port: 8080

management:
  server:
    port: 8081
    address: 0.0.0.0
  endpoints:
    web:
      exposure:
        include: prometheus
jwt:
  max-active: 1
  access-token:
    secret: ${JWT_ACCESS_KEY}
    expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRCATION_MS}
  refresh-token:
    secret: ${JWT_REFRESH_KEY}
    expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRCATION_MS}

init:
  admin:
    email: ${INIT_ADMIN_EMAIL}
    password: ${INIT_ADMIN_PASSWORD}
  user:
    email: ${INIT_USER_EMAIL}
    password: ${INIT_USER_PASSWORD}

aws:
  accessKeyId: ${AWS_S3_ACCESS_KEY}
  secretKey: ${AWS_S3_SECRET_KEY}
  region: ${AWS_S3_REGION}
  bucket: ${AWS_S3_BUCKET}
