spring:
  application:
    name: jeonggiju
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  address: 0.0.0.0
  port: 8080

management:
  server:
    port: 8081 # metric은 따로 관리
    address: 0.0.0.0
  endpoints:
    web:
      exposure:
        include: prometheus
jwt:
  max-active: 1
  access-token:
    secret: ${JWT_ACCESS_KEY}
    expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRCATION_MS}
  refresh-token:
    secret: ${JWT_REFRESH_KEY}
    expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRCATION_MS}

