name: Deploy DB, CertBot To EC2

on:
  push:
    branches:
      - deploy/directory
    paths:
      - "deploy/etc/**"
      - ".github/workflows/etc-deploy.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: AWS Resource에 접근할 수 있게 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: .env 파일 생성
        run: |
          cat > .env << EOF
          
          SPRING_DATASOURCE_URL=${{secrets.SPRING_DATASOURCE_URL}}
          SPRING_DATASOURCE_USERNAME=${{secrets.SPRING_DATASOURCE_USERNAME}}
          SPRING_DATASOURCE_PASSWORD=${{secrets.SPRING_DATASOURCE_PASSWORD}}
  
          EOF

      - name: 압축하기
        run: |
          cp deploy/etc/appspec.yml ./appspec.yml
          cp -r deploy/etc/scripts ./scripts
          cp deploy/etc/docker-compose.etc.yml ./docker-compose.etc.yml
          tar -czvf $GITHUB_SHA.tar.gz \
            appspec.yml \
            .env \
            scripts \
            docker-compose.etc.yml

      - name: S3에 프로젝트 폴더 업로드하기
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.tar.gz s3://jeongiju-life/$GITHUB_SHA.tar.gz

      - name: Code Deploy를 활용해 EC2에 프로젝트 코드 배포
        run: aws deploy create-deployment
          --application-name Keep4Life-Etc
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name keep-for-life-etc-group
          --s3-location bucket=jeongiju-life,bundleType=tgz,key=$GITHUB_SHA.tar.gz
